### ISSUE TITLE
[1]가이드 기본 환경 구성하기

### ISSUE THREAD

**Issue by tea7day** [wooritech/enumist-docs#1]
배포는 gh-pages 브랜치와 travis-ci로 배포 자동화
- 빌드 브랜치를 별도로 구성함으로써, 소스 폴더를 단순하게 하고 용량을 최적화

소스 폴더 및 vuepress 설정은 `tech-well` 참고

**Comment by wooritech** [comment]
완료

### 참고

- [Publish a Vuepress site on GitHub pages with Travis](https://itnext.io/publish-a-vuepress-site-on-github-pages-with-travis-82036243bf36)
- [Quick start: Setting up a custom domain](https://help.github.com/en/articles/quick-start-setting-up-a-custom-domain)
- [Setting up a custom subdomain](https://help.github.com/en/articles/setting-up-a-custom-subdomain)
